In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
# Dataframe
import pandas as pd

# Array
import numpy as np
import itertools

# Visualizations
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
import matplotlib.colors as colors
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS


## Warnings
import warnings
from scipy import stats
warnings.filterwarnings('ignore')

#Digital Music-Recommender

In [3]:
Rating_DM = pd.read_csv('/content/drive/MyDrive/My_DS_FT_1/ratings_Digital_Music.csv')
Rating_DM.head(2)

reviewerID        asin  overall  unixReviewTime
0  A2EFCYXHNK06IS  5555991584        5       978480000
1  A1WR23ER5HMAA9  5555991584        5       953424000

In [4]:
Rating_DM.drop(['unixReviewTime'],axis=1,inplace=True)

In [5]:
Rating_DM.rename(columns={'reviewerID':'Reviewer_ID','overall':'Rating'},inplace=True)

In [6]:
DM_meta = pd.read_json('/content/drive/MyDrive/My_DS_FT_1/meta_Digital_Music.json', orient='records', lines=True)
DM_meta.head(2)

category tech1 description fit  ...        asin imageURL imageURLHighRes details
0       []                []      ...  0001377647       []              []     NaN
1       []                []      ...  0001529145       []              []     NaN

[2 rows x 19 columns]

In [7]:
DM_meta = DM_meta[['title','asin']].copy()

###Text_Preprocessing

In [13]:
import inflect
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
import unicodedata
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize, regexp_tokenize 
from nltk.stem import PorterStemmer, WordNetLemmatizer
import re

import re, string, unicodedata
from bs4 import BeautifulSoup
from nltk import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem.lancaster import LancasterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [14]:
def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()
def remove_between_square_brackets(text):
    return re.sub('\[[^]]*\]', '', text)
def denoise_text(text):
    text = strip_html(text)
    text = remove_between_square_brackets(text)
    return text
# special_characters removal
def remove_special_characters(text, remove_digits=True):
    pattern = r'[^a-zA-z0-9\s]' if not remove_digits else r'[^a-zA-z\s]'
    text = re.sub(pattern, '', text)
    return text
def remove_non_ascii(words):
    """Remove non-ASCII characters from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = unicodedata.normalize('NFKD', word).encode('ascii', 'ignore').decode('utf-8', 'ignore')
        new_words.append(new_word)
    return new_words
def to_lowercase(words):
    """Convert all characters to lowercase from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = word.lower()
        new_words.append(new_word)
    return new_words
def remove_punctuation_and_splchars(words):
    """Remove punctuation from list of tokenized words"""
    new_words = []
    for word in words:
        new_word = re.sub(r'[^\w\s]', '', word)
        if new_word != '':
            new_word = remove_special_characters(new_word, True)
            new_words.append(new_word)
    return new_words
def replace_numbers(words):
    """Replace all interger occurrences in list of tokenized words with textual representation"""
    p = inflect.engine()
    new_words = []
    for word in words:
        if word.isdigit():
            new_word = p.number_to_words(word)
            new_words.append(new_word)
        else:
            new_words.append(word)
    return new_words
stopword_list= stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('not')
def remove_stopwords(words):
    """Remove stop words from list of tokenized words"""
    new_words = []
    for word in words:
        if word not in stopword_list:
            new_words.append(word)
    return new_words
def stem_words(words):
    """Stem words in list of tokenized words"""
    stemmer = LancasterStemmer()
    stems = []
    for word in words:
        stem = stemmer.stem(word)
        stems.append(stem)
    return stems
def lemmatize_verbs(words):
    """Lemmatize verbs in list of tokenized words"""
    lemmatizer = WordNetLemmatizer()
    lemmas = []
    for word in words:
        lemma = lemmatizer.lemmatize(word, pos='v')
        lemmas.append(lemma)
    return lemmas
def normalize(words):
    words = remove_non_ascii(words)
    words = to_lowercase(words)
    words = remove_punctuation_and_splchars(words)
    #words = remove_stopwords(words)
    return words
def lemmatize(words):
    lemmas = lemmatize_verbs(words)
    return lemmas

In [15]:
def normalize_and_lemmaize(input):
    sample = denoise_text(input)
    #sample = expand_contractions(sample)
    sample = remove_special_characters(sample)
    words = nltk.word_tokenize(sample)
    words = normalize(words)
    lemmas = lemmatize(words)
    return ' '.join(lemmas)

In [11]:
DM_meta['title'] = DM_meta['title'].map(lambda text: normalize_and_lemmaize(text))

#Recommender System

In [12]:
DM_meta.tail()

title        asin
74342                              future present nights  B01HH7D5KU
74343       tori amos little earthquakes lp vinyl record  B01HHGQXI2
74344  exo exact rd album cd with page photobook phot...  B01HHRIKKK
74345                        vanilla fudge korea edition  B01HI2B3G2
74346  cd svetlana ceca raznatovic new album autogram...  B01HIT3KZC

In [13]:
DM_meta.shape

(74347, 2)

In [14]:
Rating_DM=pd.merge(Rating_DM,DM_meta,on='asin',how='inner')
Rating_DM.head()

Reviewer_ID        asin  Rating                 title
0  A1T1OG976WVRSG  6308051551       5  dont drink his blood
1  A2Z4YICLD9UP4Y  6308051551       5  dont drink his blood
2  A3KZXLERHIUJLK  B000006045       5             mezzanine
3  A1YEKM4E9ANS1R  B000006045       5             mezzanine
4  A261J1N8C09GFQ  B000006045       4             mezzanine

In [15]:
Rating_DM.isnull().sum()

Reviewer_ID    0
asin           0
Rating         0
title          0
dtype: int64

In [16]:
Rating_DM[Rating_DM.duplicated(['Reviewer_ID','asin'], keep= False)]

Reviewer_ID        asin  Rating        title
333  ALKI4CNQ7NHHG  B0002YLAYE       4  mamani live
334  ALKI4CNQ7NHHG  B0002YLAYE       4  mamani live

In [17]:
Rating_DM = Rating_DM.drop_duplicates(['asin', 'Reviewer_ID'], keep = 'first')

In [18]:
ratings_pivot = Rating_DM.pivot(index='asin',columns= 'Reviewer_ID',values='Rating').fillna(0)
ratings_pivot.head(2)

Reviewer_ID  A063435134NW8TXB90EF1  ...  AZQRFW9FAQ2RJ
asin                                ...               
6308051551                     0.0  ...            0.0
B000006045                     0.0  ...            5.0

[2 rows x 1112 columns]

In [19]:
ratings_pivot.shape

(290, 1112)

In [20]:
from sklearn.model_selection import train_test_split
traind, testd = train_test_split(ratings_pivot, test_size=0.25,random_state=42)

In [21]:
train = traind.values
test = testd.values

In [22]:
sp = float(len(train.nonzero()[0]))
sp /= (train.shape[0] * train.shape[1])
sp *= 100
print ('Sparsity: {:5.2f}%'.format(sp))

Sparsity:  0.43%


In [23]:
def item_similarity(ratings, epsilon=1e-9):
    sim = ratings.T.dot(ratings) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [24]:
similarity_item = item_similarity(train)

In [25]:
def predict_item(ratings, similarity):
    return ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [26]:
pred_item = predict_item(train, similarity_item)

In [27]:
pred_item[:4, :4]

array([[3.99817926e-10, 4.62425311e-12, 3.86323798e-11, 4.62425311e-12],
       [2.70587455e-10, 3.12958674e-12, 2.61454943e-11, 3.12958674e-12],
       [2.70587455e-10, 3.12958674e-12, 2.61454944e-11, 3.12958674e-12],
       [5.48547755e-10, 6.34444705e-12, 5.30033894e-11, 6.34444705e-12]])

In [28]:
Rating_DM.head()

Reviewer_ID        asin  Rating                 title
0  A1T1OG976WVRSG  6308051551       5  dont drink his blood
1  A2Z4YICLD9UP4Y  6308051551       5  dont drink his blood
2  A3KZXLERHIUJLK  B000006045       5             mezzanine
3  A1YEKM4E9ANS1R  B000006045       5             mezzanine
4  A261J1N8C09GFQ  B000006045       4             mezzanine

In [29]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

In [30]:
print ('Item-based CF MSE: {}'.format(str(get_mse(pred_item, test))))

Item-based CF MSE: 20.264817540473995


In [31]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(traind) 

ctrain = cosine_similarity(r_mat_tr)

In [32]:
svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 

ctest = cosine_similarity(r_mat_tr)

In [33]:
print (' CF MSE:{} '.format(str(get_mse(ctrain, ctest))))

 CF MSE:0.09770928099867238 


In [34]:
Rating_DM1 = Rating_DM.sort_values(by='Rating')
Rating_DM1 = Rating_DM1.reset_index(drop=True)
count_Reviewers = Rating_DM1.groupby("Reviewer_ID", as_index=False).count()

In [35]:
count_Reviewers.shape

(1112, 4)

In [36]:
count_prod = Rating_DM.groupby("asin", as_index=False).mean()

In [37]:
prod_df = count_prod[['asin']]
prod_df.head()

asin
0  6308051551
1  B000006045
2  B0002YLAYE
3  B000EGCV3O
4  B000M3WHHE

In [38]:
Reviewer_df = count_Reviewers[['Reviewer_ID']]
Reviewer_df.head()

Reviewer_ID
0  A063435134NW8TXB90EF1
1   A0925444HBYYHNWNZOGY
2         A101KI6HJUPHM0
3   A1041053SID37WN8GTT8
4         A1079CQTAUIX6J

In [39]:
df_clean_matrix = Rating_DM.pivot(index='asin', columns='Reviewer_ID', values='Rating').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).values
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [40]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.01724138, -0.01724138, -0.01724138, ..., -0.01724138,
        -0.01724138, -0.01724138],
       [-0.01724138, -0.01724138, -0.01724138, ..., -0.01724138,
        -0.01724138, -0.01724138],
       [-0.01724138, -0.01724138, -0.01724138, ..., -0.01724138,
        -0.01724138, -0.01724138],
       ...,
       [-0.01724138, -0.01724138, -0.01724138, ..., -0.01724138,
        -0.01724138, -0.01724138],
       [-0.0137931 , -0.0137931 , -0.0137931 , ..., -0.0137931 ,
        -0.0137931 , -0.0137931 ],
       [-0.01724138,  4.98275862, -0.01724138, ..., -0.01724138,
        -0.01724138, -0.01724138]])

In [41]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

# sigma: singular values
# Vt : right singular vectors
# U :  left singular vectors

In [42]:
sigma = np.diag(sigma)

In [43]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['Reviewer_ID'] = Reviewer_df
preds_df.set_index('Reviewer_ID', inplace=True)
preds_df.head()

asin                   6308051551  B000006045  ...  B00LMR3GLK  B00LNHWB0G
Reviewer_ID                                    ...                        
A063435134NW8TXB90EF1    0.021500    0.000022  ...    0.021500    0.021390
A0925444HBYYHNWNZOGY     0.000046   -0.000002  ...    0.000046    0.000187
A101KI6HJUPHM0          -0.000332   -0.000010  ...   -0.000332    0.000853
A1041053SID37WN8GTT8     0.000046   -0.000002  ...    0.000046    0.000187
A1079CQTAUIX6J          -0.007602    0.000133  ...   -0.007602   -0.006924

[5 rows x 290 columns]

In [44]:
Rating_DM.tail()

Reviewer_ID        asin  Rating                 title
1223  A12DQZKRKTNF5E  B00LI9NFOA       5     party for america
1224   A8IDSLXQRY7D7  B00LLRI9HM       3    fire for your fire
1225   AMVBLG7IPYJVZ  B00LMR3GLK       5     bon iver and more
1226   AHZ2KVZZ2IYO8  B00LMR3GLK       5     bon iver and more
1227   A25OYT7U3IVVT  B00LNHWB0G       5  jamie grace and more

In [45]:
def recommend_it(predictions_df, prod_df, Rating_DM, num_recommendations=10,Reviewer_ID='A063435134NW8TXB90EF1'):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc[Reviewer_ID].sort_values(ascending=False)
    
    # Get the user's data and merge in the item information.
    user_data = Rating_DM[Rating_DM.Reviewer_ID == Reviewer_ID]
    user_full = (user_data.merge(prod_df, how = 'left', left_on = 'asin', right_on = 'asin').
                     sort_values(['Rating'], ascending=False)
                 )

    print ('User {0} has already purchased {1} items from Digital Music Category.'.format(Reviewer_ID, user_full.shape[0]))
    print ('Top {0} Product IDs Recommended to the User.'.format(num_recommendations))

    recommendations = (prod_df[~prod_df['asin'].isin(user_full['asin'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'asin',
               right_on = 'asin').
         rename(columns = {Reviewer_ID: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    topk=recommendations.merge(Rating_DM, right_on = 'asin',left_on='asin').drop_duplicates(
    ['asin','title'])[['asin','title']]

    return topk

In [46]:
recommend_it(preds_df, prod_df, Rating_DM, 6)

User A063435134NW8TXB90EF1 has already purchased 1 items from Digital Music Category.
Top 6 Product IDs Recommended to the User.


asin                            title
0   B000T0FR0Y                        justments
12  B00KUZ7IOQ            indie feel good music
17  B00KUZWMLK                    great s songs
24  B00KWO34XY  the after party late night beat
29  B00KWN7K7Q           the lumineers and more
33  B00KMO6FP8           foo fighters top songs

In [47]:
recommend_it(preds_df, prod_df, Rating_DM, 10,'A25OYT7U3IVVT')

User A25OYT7U3IVVT has already purchased 1 items from Digital Music Category.
Top 10 Product IDs Recommended to the User.


asin                            title
0   B000T0FR0Y                        justments
12  B00KUZ7IOQ            indie feel good music
17  B00KUZWMLK                    great s songs
24  B00KWO34XY  the after party late night beat
29  B00KWN7K7Q           the lumineers and more
33  B00KMO6FP8           foo fighters top songs
39  B00L1TACZM         great classic jazz songs
44  B00KUYTBEC            powerful women of pop
50  B00KUXEAW6          joshua radins top songs
52  B00L8BN6MY          britney spear top songs

#Musical Instruments-Recommender

In [26]:
Rating_MI = pd.read_csv('/content/drive/MyDrive/My_DS_FT_1/ratings_Musical_Instruments.csv')
Rating_MI.head(2)

reviewerID      asin  overall  unixReviewTime
0  A1YS9MDZP93857   6428320        3      1394496000
1  A3TS466QBAWB9D  14072149        5      1370476800

In [27]:
Rating_MI.drop(['unixReviewTime'],axis=1,inplace=True)

In [28]:
Rating_MI.rename(columns={'reviewerID':'Reviewer_ID','overall':'Rating'},inplace=True)

In [29]:
MI_meta = pd.read_json('/content/drive/MyDrive/My_DS_FT_1/meta_Musical_Instruments.json', orient='records', lines=True)
MI_meta.head(2)

category  ... details
0  [Musical Instruments, Drums & Percussion, Hand...  ...     NaN
1  [Musical Instruments, Drums & Percussion, Hand...  ...     NaN

[2 rows x 19 columns]

In [30]:
MI_meta = MI_meta[['title','asin']].copy()

In [31]:
MI_meta['title'] = MI_meta['title'].map(lambda text: normalize_and_lemmaize(text))

In [32]:
Rating_MI=pd.merge(Rating_MI,MI_meta,on='asin',how='inner')
Rating_MI.head()

Reviewer_ID  ...                                              title
0   ALQ1N9BFCI338  ...                      piano wizard premier wmidiusb
1  A1W8VIM71GAG1P  ...                      piano wizard premier wmidiusb
2  A1F2BFHG2HHKSO  ...                      piano wizard premier wmidiusb
3  A11OWHWCBEDVXN  ...                      piano wizard premier wmidiusb
4  A13QQ9QCR2PJCH  ...  inspiration station progressions of expression...

[5 rows x 4 columns]

In [33]:
Rating_MI.isnull().sum()

Reviewer_ID    0
asin           0
Rating         0
title          0
dtype: int64

In [34]:
Rating_MI[Rating_MI.duplicated(['Reviewer_ID','asin'], keep= False)]

Reviewer_ID  ...                                              title
49      A3GW8K7A7TNX7Z  ...                      hohner usa beginner harmonica
50      A3GW8K7A7TNX7Z  ...                      hohner usa beginner harmonica
51      A1UZU58XBGCB6U  ...                      hohner usa beginner harmonica
52      A1UZU58XBGCB6U  ...                      hohner usa beginner harmonica
53       ADSSBM3KZG3BJ  ...                      hohner usa beginner harmonica
...                ...  ...                                                ...
116430  A1UO3BBM0ZYG5T  ...            hameln rosewood alto recorder with case
116431  A1P3E3AWA224GG  ...            hameln rosewood alto recorder with case
116432  A1P3E3AWA224GG  ...            hameln rosewood alto recorder with case
116433  A27F8UBFMB8OBN  ...  motu mx version multi synthesizer virtual inst...
116434  A27F8UBFMB8OBN  ...  motu mx version multi synthesizer virtual inst...

[116386 rows x 4 columns]

In [35]:
Rating_MI = Rating_MI.drop_duplicates(['asin', 'Reviewer_ID'], keep = 'first')

In [36]:
Rating_MI.shape

(275285, 4)

In [37]:
count_prd_id=Rating_MI['asin'].value_counts()
count_cust_id=Rating_MI['Reviewer_ID'].value_counts()
Rating_MI=Rating_MI[Rating_MI['Reviewer_ID'].isin(count_cust_id[count_cust_id >=5].index)]
Rating_MI=Rating_MI[Rating_MI['asin'].isin(count_prd_id[count_prd_id >=5].index)]

In [38]:
Rating_MI.shape

(26925, 4)

In [39]:
ratings_pivot = Rating_MI.pivot(index='asin',columns= 'Reviewer_ID',values='Rating').fillna(0)
ratings_pivot.head(2)

Reviewer_ID  A00625243BI8W1SSZNLMD  ...  AZY7YVOUIBM8Q
asin                                ...               
9792372326                     0.0  ...            0.0
B00001W0DT                     0.0  ...            0.0

[2 rows x 4538 columns]

In [40]:
ratings_pivot.shape

(7306, 4538)

In [41]:
from sklearn.model_selection import train_test_split
traind, testd = train_test_split(ratings_pivot, test_size=0.25,random_state=42)

In [42]:
train = traind.values
test = testd.values

In [43]:
sp = float(len(train.nonzero()[0]))
sp /= (train.shape[0] * train.shape[1])
sp *= 100
print ('Sparsity: {:5.2f}%'.format(sp))

Sparsity:  0.08%


In [44]:
def item_similarity(ratings, epsilon=1e-9):
    sim = ratings.T.dot(ratings) + epsilon
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [45]:
similarity_item = item_similarity(train)

In [46]:
def predict_item(ratings, similarity):
    return ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [47]:
pred_item = predict_item(train, similarity_item)

In [48]:
pred_item[:4, :4]

array([[3.00458205e-12, 5.75830737e-11, 1.06571627e-10, 8.82918293e-12],
       [2.71352038e-12, 5.20048516e-11, 9.62477568e-11, 7.97387702e-12],
       [1.11485598e-12, 2.13663108e-11, 3.95436084e-11, 3.27608539e-12],
       [2.41909191e-02, 4.56316882e-10, 8.44526518e-10, 6.99668317e-11]])

In [49]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

In [50]:
print ('Item-based CF MSE: {}'.format(str(get_mse(pred_item, test))))

Item-based CF MSE: 20.192563445787883


In [52]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(traind) 

ctrain = cosine_similarity(r_mat_tr)

In [53]:
svd = TruncatedSVD(n_components=50, n_iter=7, random_state=42)
r_mat_tr=svd.fit_transform(testd) 

ctest = cosine_similarity(r_mat_tr)

In [54]:
print (' CF MSE:{} '.format(str(get_mse(ctrain, ctest))))

 CF MSE:0.05128943863882113 


In [56]:
Rating_MI1 = Rating_MI.sort_values(by='Rating')
Rating_MI1 = Rating_MI1.reset_index(drop=True)
count_Reviewers = Rating_MI1.groupby("Reviewer_ID", as_index=False).count()

In [57]:
count_prod = Rating_MI.groupby("asin", as_index=False).mean()

In [58]:
prod_df = count_prod[['asin']]
prod_df.head()

asin
0  9792372326
1  B00001W0DT
2  B00001WRI0
3  B00004U8LC
4  B00004UE29

In [59]:
Reviewer_df = count_Reviewers[['Reviewer_ID']]
Reviewer_df.head()

Reviewer_ID
0  A00625243BI8W1SSZNLMD
1  A01458943UKX2HCM0VVN0
2  A09109152HKAJDLWWV6HV
3         A10044ECXDUVKS
4         A100BB8D2BVA20

In [60]:
df_clean_matrix = Rating_MI.pivot(index='asin', columns='Reviewer_ID', values='Rating').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).values
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [61]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.00328497, -0.00328497, -0.00328497, ..., -0.00328497,
        -0.00328497, -0.00328497],
       [-0.00191623, -0.00191623, -0.00191623, ..., -0.00191623,
        -0.00191623, -0.00191623],
       [-0.00177936, -0.00177936, -0.00177936, ..., -0.00177936,
        -0.00177936, -0.00177936],
       ...,
       [-0.00191623, -0.00191623, -0.00191623, ..., -0.00191623,
        -0.00191623, -0.00191623],
       [-0.00547495, -0.00547495, -0.00547495, ..., -0.00547495,
        -0.00547495, -0.00547495],
       [-0.00205311, -0.00205311, -0.00205311, ..., -0.00205311,
        -0.00205311, -0.00205311]])

In [62]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

# sigma: singular values
# Vt : right singular vectors
# U :  left singular vectors

In [63]:
sigma = np.diag(sigma)
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['Reviewer_ID'] = Reviewer_df
preds_df.set_index('Reviewer_ID', inplace=True)
preds_df.head()

asin                   9792372326  B00001W0DT  ...  B00J4TBMVO  B00JBIVXGC
Reviewer_ID                                    ...                        
A00625243BI8W1SSZNLMD   -0.008295   -0.006250  ...    0.034575    0.058234
A01458943UKX2HCM0VVN0    0.001676    0.002034  ...    0.001412    0.001007
A09109152HKAJDLWWV6HV    0.001834    0.001899  ...    0.001103    0.000537
A10044ECXDUVKS           0.010277    0.007945  ...    0.021868    0.033554
A100BB8D2BVA20           0.001587    0.001718  ...    0.000922    0.000301

[5 rows x 7306 columns]

In [68]:
def recommend_it(predictions_df, prod_df, Rating_MI, num_recommendations=10,Reviewer_ID='A00625243BI8W1SSZNLMD'):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc[Reviewer_ID].sort_values(ascending=False)
    
    # Get the user's data and merge in the item information.
    user_data = Rating_MI[Rating_MI.Reviewer_ID == Reviewer_ID]
    user_full = (user_data.merge(prod_df, how = 'left', left_on = 'asin', right_on = 'asin').
                     sort_values(['Rating'], ascending=False)
                 )

    print ('User {0} has already purchased {1} items from Musical Instruments Category.'.format(Reviewer_ID, user_full.shape[0]))
    print ('Top {0} Product IDs Recommended to the User.'.format(num_recommendations))

    recommendations = (prod_df[~prod_df['asin'].isin(user_full['asin'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'asin',
               right_on = 'asin').
         rename(columns = {Reviewer_ID: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )
    topk=recommendations.merge(Rating_MI, right_on = 'asin',left_on='asin').drop_duplicates(
    ['asin','title'])[['asin','title']]

    return topk

In [69]:
recommend_it(preds_df, prod_df, Rating_MI, 6)

User A00625243BI8W1SSZNLMD has already purchased 5 items from Musical Instruments Category.
Top 6 Product IDs Recommended to the User.


asin                                              title
0    B000RNB720                           truetone spot combo pack
67   B0002GLDQM                          dunlop si ergo pickholder
148  B001PGXKC8  planet wave pwcgtp classic series instrument c...
216  B0006NDF8A       onstage xcg black tripod guitar stand single
302  B0002E2KPC                        dunlop acoustic guitar fret
385  B0002GMGYA   planet wave classic series instrument cable feet

In [70]:
recommend_it(preds_df, prod_df, Rating_MI, 10,'A306NASGVUDFKF')

User A306NASGVUDFKF has already purchased 7 items from Musical Instruments Category.
Top 10 Product IDs Recommended to the User.


asin                                              title
0    B0002E3CHC  daddario exp with ny steel phosphor bronze aco...
57   B0073XCXHA  snark sn super tight tuner with chromacast gui...
95   B000RNB720                           truetone spot combo pack
162  B004XNK7AI    snark sn tuner for guitar bass and violin black
243  B000B6FBA2                   planet wave ns guitar capo black
277  B0002OOMU8                      dunlop series pickholder pack
324  B00154OJOI                                      dava grip tip
362  B000OMG0KI  daddario accessories humidipak twoway humidifi...
389  B00FXKIG5I         snark s son of snark guitar and bass tuner
400  B0002D0CEO     dunlop tortex standard mm red guitar pick pack